---
- name: Update all packages
  yum:
    name: '*'
    state: latest

- name: Install Docker
  yum:
    name: docker
    state: latest

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Append ec2-user to the docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: yes

- name: Fix docker permission without reboot
  ansible.builtin.file:
    path: /var/run/docker.sock
    owner: ec2-user
    group: docker
    mode: '0666'

- name: Install or downgrade urllib3
  pip:
    name: urllib3<2.0
    state: present
    executable: pip3

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: latest
    executable: pip3


